env:
  browser: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2019
  sourceType: module
plugins:
  - react
rules: {
  "react/prop-types": 0
}
